/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ExerciciosRouteImport } from './routes/exercicios'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as RotinasRouteImport } from './routes/rotinas'
import { Route as ExecutarWorkoutIdRouteImport } from './routes/executar.$workoutId'
import { Route as ExercicioExerciseIdRouteImport } from './routes/exercicio.$exerciseId'
import { Route as TreinoWorkoutIdRouteImport } from './routes/treino.$workoutId'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as RelatoriosRouteImport } from './routes/relatorios'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ExerciciosRoute = ExerciciosRouteImport.update({
  id: '/exercicios',
  path: '/exercicios',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const RotinasRoute = RotinasRouteImport.update({
  id: '/rotinas',
  path: '/rotinas',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutarWorkoutIdRoute = ExecutarWorkoutIdRouteImport.update({
  id: '/executar/$workoutId',
  path: '/executar/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercicioExerciseIdRoute = ExercicioExerciseIdRouteImport.update({
  id: '/exercicio/$exerciseId',
  path: '/exercicio/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const TreinoWorkoutIdRoute = TreinoWorkoutIdRouteImport.update({
  id: '/treino/$workoutId',
  path: '/treino/$workoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/exercicios': typeof ExerciciosRoute
  '/historico': typeof HistoricoRoute
  '/rotinas': typeof RotinasRoute
  '/executar/$workoutId': typeof ExecutarWorkoutIdRoute
  '/exercicio/$exerciseId': typeof ExercicioExerciseIdRoute
  '/treino/$workoutId': typeof TreinoWorkoutIdRoute
  '/progresso': typeof ProgressoRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/exercicios': typeof ExerciciosRoute
  '/historico': typeof HistoricoRoute
  '/rotinas': typeof RotinasRoute
  '/executar/$workoutId': typeof ExecutarWorkoutIdRoute
  '/exercicio/$exerciseId': typeof ExercicioExerciseIdRoute
  '/treino/$workoutId': typeof TreinoWorkoutIdRoute
  '/progresso': typeof ProgressoRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/exercicios': typeof ExerciciosRoute
  '/historico': typeof HistoricoRoute
  '/rotinas': typeof RotinasRoute
  '/executar/$workoutId': typeof ExecutarWorkoutIdRoute
  '/exercicio/$exerciseId': typeof ExercicioExerciseIdRoute
  '/treino/$workoutId': typeof TreinoWorkoutIdRoute
  '/progresso': typeof ProgressoRoute
  '/relatorios': typeof RelatoriosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/configuracoes'
    | '/exercicios'
    | '/historico'
    | '/rotinas'
    | '/executar/$workoutId'
    | '/exercicio/$exerciseId'
    | '/treino/$workoutId'
    | '/progresso'
    | '/relatorios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/configuracoes'
    | '/exercicios'
    | '/historico'
    | '/rotinas'
    | '/executar/$workoutId'
    | '/exercicio/$exerciseId'
    | '/treino/$workoutId'
    | '/progresso'
    | '/relatorios'
  id:
    | '__root__'
    | '/'
    | '/configuracoes'
    | '/exercicios'
    | '/historico'
    | '/rotinas'
    | '/executar/$workoutId'
    | '/exercicio/$exerciseId'
    | '/treino/$workoutId'
    | '/progresso'
    | '/relatorios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ExerciciosRoute: typeof ExerciciosRoute
  HistoricoRoute: typeof HistoricoRoute
  RotinasRoute: typeof RotinasRoute
  ExecutarWorkoutIdRoute: typeof ExecutarWorkoutIdRoute
  ExercicioExerciseIdRoute: typeof ExercicioExerciseIdRoute
  TreinoWorkoutIdRoute: typeof TreinoWorkoutIdRoute
  ProgressoRoute: typeof ProgressoRoute
  RelatoriosRoute: typeof RelatoriosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicios': {
      id: '/exercicios'
      path: '/exercicios'
      fullPath: '/exercicios'
      preLoaderRoute: typeof ExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rotinas': {
      id: '/rotinas'
      path: '/rotinas'
      fullPath: '/rotinas'
      preLoaderRoute: typeof RotinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executar/$workoutId': {
      id: '/executar/$workoutId'
      path: '/executar/$workoutId'
      fullPath: '/executar/$workoutId'
      preLoaderRoute: typeof ExecutarWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercicio/$exerciseId': {
      id: '/exercicio/$exerciseId'
      path: '/exercicio/$exerciseId'
      fullPath: '/exercicio/$exerciseId'
      preLoaderRoute: typeof ExercicioExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treino/$workoutId': {
      id: '/treino/$workoutId'
      path: '/treino/$workoutId'
      fullPath: '/treino/$workoutId'
      preLoaderRoute: typeof TreinoWorkoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ExerciciosRoute: ExerciciosRoute,
  HistoricoRoute: HistoricoRoute,
  RotinasRoute: RotinasRoute,
  ExecutarWorkoutIdRoute: ExecutarWorkoutIdRoute,
  ExercicioExerciseIdRoute: ExercicioExerciseIdRoute,
  TreinoWorkoutIdRoute: TreinoWorkoutIdRoute,
  ProgressoRoute: ProgressoRoute,
  RelatoriosRoute: RelatoriosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
